<?xml version="1.0"?>
<!DOCTYPE bank [
<!ELEMENT costumer (cid,name,address,phone,email)>
<!ELEMENT cid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email(#PCDATA)>
<!ELEMENT account(Aid,bid,cid,Acctype,balance)>
<!ELEMENT Aid(#PCDATA)>
<!ELEMENT bid(#PCDATA)>
<!ELEMENT cid(#PCDATA)>
<!ELEMENT Acctype(#PCDATA)>
<!ELEMENT balance(#PCDATA)>
<!ELEMENT employee(empid,name,designation,doj,salary,address)>
<!ELEMENT empid(#PCDATA)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT designation(#PCDATA)>
<!ELEMENT doj(#PCDATA)>
<!ELEMENT salary(#PCDATA)>
<!ELEMENT address
(#PCDATA)>
]>

<bank>
    <costumer>
        <cid>1</cid>
        <name>Karina</name>
        <address>Itahari</address>
        <phone>980000000</phone>
        <email>karinarai@gmail.com</email>
    </costumer>
    <account>
        <Aid>123</Aid>
        <bid>456</bid>
        <cid>111</cid>
        <Acctype>Saving</Acctype>
        <balance>120000</balance>
    </account>
    <employee>
    <empid>876</empid>
    <name>Ram</name>
    <designation>Manager</designation>
    <doj>aug 23 2022</doj>
    <salary>340000</salary>
    <address>Itahari</address>
    </employee>
</bank>